default_agent: test
agents:
  test:
    name: test
    entrypoint: /home/carlos/Documentos/Agent-core-handson/myagent.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: docker
    source_path: /home/carlos/Documentos/Agent-core-handson
    aws:
      execution_role: arn:aws:iam::249127818475:role/agentcore-role-1
      execution_role_auto_create: true
      account: '249127818475'
      region: sa-east-1
      ecr_repository: 249127818475.dkr.ecr.sa-east-1.amazonaws.com/bedrock-agentcore-test
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: null
      agent_arn: null
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-test-builder
      execution_role: arn:aws:iam::249127818475:role/AmazonBedrockAgentCoreSDKCodeBuild-sa-east-1-9f86d08188
      source_bucket: bedrock-agentcore-codebuild-sources-249127818475-sa-east-1
    memory:
      mode: STM_ONLY
      memory_id: test_mem-K8sqDZ5ZIT
      memory_arn: arn:aws:bedrock-agentcore:sa-east-1:249127818475:memory/test_mem-K8sqDZ5ZIT
      memory_name: test_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: true
      was_created_by_toolkit: true
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
